name: Knit RMD to MD

on:
  push:
    paths:
      - 'final_project.Rmd'

jobs:
  knit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install pandoc
        run: |
          sudo apt-get install -y pandoc

      - name: Install Rmarkdown
        run: |
          if ! Rscript -e "if (!requireNamespace('rmarkdown', quietly = TRUE)) install.packages('rmarkdown', repos='http://cran.rstudio.com/')"; then
            echo "Failed to install rmarkdown"
            exit 1
          fi

      - name: Install other dependencies rquired for final_project.Rmd
        run: |
          Rscript -e "if (!requireNamespace('ggplot2', quietly = TRUE)) install.packages('ggplot2', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('readxl', quietly = TRUE)) install.packages('readxl', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('dplyr', quietly = TRUE)) install.packages('dplyr', repos='http://cran.rstudio.com/')"

      - name: Copy final_project.Rmd to README.Rmd
        run: cp final_project.Rmd README.Rmd

      - name: Knit README.Rmd to README.md
        run: Rscript -e "rmarkdown::render('README.Rmd', output_format='github_document')"

      - name: Knit README.Rmd to README.md
        run: Rscript -e "rmarkdown::render('README.Rmd', output_format = 'github_document', output_file = 'README.md')"

      - name: Commit and Push README.md
        run: |
          git config --global user.name 'Logan Jorgensen'
          git config --global user.email 'contact.jorgensen@gmail.com'
          git add README.md
          git commit -m "Update README.md"
          git push
